import { ProductData } from "../../../payloads/responses/ProductData.model";

const fakeProductList: ProductData[] = [
  {
    productId: 1,
    productCode: "P001",
    createDate: new Date("2023-05-15"),
    productName: "Sản phẩm 1",
    price: "50 USD",
    spotlightVideoImageUrl: "spotlight_video_url_1",
    spotlightVideoImageName: "spotlight_video_name_1",
    imageUrl: "product_image_url_1",
    imageName: "product_image_name_1",
    description: "Mô tả sản phẩm 1",
    categoryId: 1,
    categoryName: "Danh mục 1",
    brandId: 1,
  },
  {
    productId: 2,
    productCode: "P002",
    createDate: new Date("2023-06-20"),
    productName: "Sản phẩm 2",
    price: "45 USD",
    spotlightVideoImageUrl: "spotlight_video_url_2",
    spotlightVideoImageName: "spotlight_video_name_2",
    imageUrl: "product_image_url_2",
    imageName: "product_image_name_2",
    description: "Mô tả sản phẩm 2",
    categoryId: 2,
    categoryName: "Danh mục 2",
    brandId: 1,
  },
  {
    productId: 3,
    productCode: "P003",
    createDate: new Date("2023-07-10"),
    productName: "Sản phẩm 3",
    price: "55 USD",
    spotlightVideoImageUrl: "spotlight_video_url_3",
    spotlightVideoImageName: "spotlight_video_name_3",
    imageUrl: "product_image_url_3",
    imageName: "product_image_name_3",
    description: "Mô tả sản phẩm 3",
    categoryId: 1,
    categoryName: "Danh mục 1",
    brandId: 2,
  },
  {
    productId: 4,
    productCode: "P004",
    createDate: new Date("2023-08-05"),
    productName: "Sản phẩm 4",
    price: "60 USD",
    spotlightVideoImageUrl: "spotlight_video_url_4",
    spotlightVideoImageName: "spotlight_video_name_4",
    imageUrl: "product_image_url_4",
    imageName: "product_image_name_4",
    description: "Mô tả sản phẩm 4",
    categoryId: 2,
    categoryName: "Danh mục 2",
    brandId: 2,
  },
  {
    productId: 5,
    productCode: "P005",
    createDate: new Date("2023-09-15"),
    productName: "Sản phẩm 5",
    price: "65 USD",
    spotlightVideoImageUrl: "spotlight_video_url_5",
    spotlightVideoImageName: "spotlight_video_name_5",
    imageUrl: "product_image_url_5",
    imageName: "product_image_name_5",
    description: "Mô tả sản phẩm 5",
    categoryId: 1,
    categoryName: "Danh mục 1",
    brandId: 1,
  },
  {
    productId: 6,
    productCode: "P006",
    createDate: new Date("2023-10-20"),
    productName: "Sản phẩm 6",
    price: "70 USD",
    spotlightVideoImageUrl: "spotlight_video_url_6",
    spotlightVideoImageName: "spotlight_video_name_6",
    imageUrl: "product_image_url_6",
    imageName: "product_image_name_6",
    description: "Mô tả sản phẩm 6",
    categoryId: 2,
    categoryName: "Danh mục 2",
    brandId: 1,
  },
  {
    productId: 7,
    productCode: "P007",
    createDate: new Date("2023-11-10"),
    productName: "Sản phẩm 7",
    price: "75 USD",
    spotlightVideoImageUrl: "spotlight_video_url_7",
    spotlightVideoImageName: "spotlight_video_name_7",
    imageUrl: "product_image_url_7",
    imageName: "product_image_name_7",
    description: "Mô tả sản phẩm 7",
    categoryId: 1,
    categoryName: "Danh mục 1",
    brandId: 2,
  },
  {
    productId: 8,
    productCode: "P008",
    createDate: new Date("2023-12-01"),
    productName: "Sản phẩm 8",
    price: "80 USD",
    spotlightVideoImageUrl: "spotlight_video_url_8",
    spotlightVideoImageName: "spotlight_video_name_8",
    imageUrl: "product_image_url_8",
    imageName: "product_image_name_8",
    description: "Mô tả sản phẩm 8",
    categoryId: 2,
    categoryName: "Danh mục 2",
    brandId: 2,
  },
];

export default fakeProductList;
